version: '2'
services:
  nextgw:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    network_mode: host
    privileged: true
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: 'unix:path=/host/run/dbus/system_bus_socket'
    ports:
      - '80:80'
    labels:
      io.balena.features.dbus: '1'
    entrypoint:
      - sh
      - ./start.sh
    cap_add:
      - NET_ADMIN

